included:
  - Sources
  - Tests

disabled_rules:
  - trailing_comma

excluded:
  - .build
  - .codex

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - sorted_imports
  - vertical_parameter_alignment_on_call

line_length:
  warning: 120
  error: 150

opening_brace:
  ignore_multiline_statement_conditions: true

type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 20

custom_rules:
  no_any_type:
    name: "No Any Type"
    regex: "\\bAny\\b"
    message: "`Any` is prohibited. Use a concrete type, `any Protocol`, or generics."
    severity: error
    match_kinds:
      - identifier
  no_throw_in_domain:
    name: "No Throw In Domain"
    included:
      - Sources/Domain
    regex: "\\b(throw|throws|rethrows)\\b"
    message: "Domain layer must not use throw/throws. Use Result-based modeling."
    severity: error
    match_kinds:
      - keyword
